<?php

return [ // LA TABLA CON SUS CAMPOS
    'action' => [
        'ID_IDENTIFICATION', 
        'PID_GROUP', 
        'PID_INTERNATIONAL_GROUP', 
        'PID_PARTNER', 
        'PID_REVENDEUR', 
        'PID_SUSPECTS', 
        'ACTIVITE', 
        'ACTIVITY_INAIL_CLASSIFICATION', 
        'ACTIVITY_INPS_CLASSIFICATION', 
        'ADRESSE1', 
        'ADRESSE2', 
        'ADRESSE3', 
        'AT_AO_BROKER', 
        'AT_AO_CONTRACT_ENDING_DATE', 
        'AT_AO_CONTRACT_STARTING_DATE', 
        'AT_AO_INSURANCE', 
        'AT_AO_POLICE_NBRE', 
        'AUDITEUR', 
        'BELSPO', 
        'BENEFITS', 
        'BITRIX_KEY', 
        'CA', 
        'CA_2', 
        'CA_2_ANNEE', 
        'CA_ANNEE', 
        'CCNL_MAIN', 
        'CCNL_SECONDARY', 
        'CLIENT_SECURE', 
        'CODE_CLIENT', 
        'CODE_NAF', 
        'CODE_NAF2', 
        'CODE_POSTAL', 
        'CODE_TVA_INTRA', 
        'COMPANY_CLASSIFICATION', 
        'COMPL_RAISON_SOC', 
        'CONVENTION_COLLECTIVE_IDCC', 
        'CONVENTION_COLLECTIVE_TITRE', 
        'CREATION_DATE', 
        'CSC_CODE_INPS_CLASSIFICATION', 
        'CSP_ETRANGER', 
        'CSP_FRANCE', 
        'CUSTOMER_RELATIONSHIP_MANAGER', 
        'DIGITAL_INVOICE_ONLY', 
        'DIGITAL_INVOICE_REFUSED', 
        'DMFA_REQUEST', 
        'EFFECTIF', 
        'EFFECTIF_2', 
        'EFFECTIF_NUM', 
        'EFFECTIF_NUM_2', 
        'EMAIL', 
        'EMPLOYEES_USE_CARS', 
        'EPISODES_OF_INTEGRATION_OR_SOLIDARITY', 
        'EPISODES_OF_INTEGRATION_OR_SOLIDARITY_YEAR', 
        'FAX', 
        'FISCAL_CLOSING', 
        'FORME_JURIDIQUE', 
        'FUSION', 
        'GROUP', 
        'HEAD_OFFICE', 
        'HEAD_OFFICE_NAME', 
        'INCORPORATION', 
        'INTERNATIONAL', 
        'INTERNATIONAL_COMPANY', 
        'INTERNATIONAL_GROUP', 
        'INTERNATIONAL_HEAD_OFFICE', 
        'INTERNATIONAL_HEAD_OFFICE_TYPE', 
        'INTERNATIONAL_RESPONSIBLE', 
        'INTERNATIONAL_SECTOR', 
        'INVOICE_LANGUAGE', 
        'IP_BELGIUM', 
        'IP_BRAZIL', 
        'IP_CHILE', 
        'IP_COUNTRY_OF_THE_DECISION_MAKER', 
        'IP_FRANCE', 
        'IP_GERMANY', 
        'IP_ITALY', 
        'IP_POLAND', 
        'IP_SPAIN', 
        'IWT', 
        'KEY_ACCOUNT', 
        'LIQUIDATION', 
        'LISTED_COMPANY', 
        'MAPS_ADRESSE', 
        'MAPS_ADRESSE_PHYSIQUE', 
        'MAPS_CODE_POSTAL', 
        'MAPS_PAYS', 
        'MAPS_VILLE', 
        'NB_ETABLISSEMENTS', 
        'NET_PROFIT', 
        'NOM_EXPEDITEUR', 
        'NUMBER_MANAGERS', 
        'N_CANAL_SFTP', 
        'ONSS_PROTOCOL', 
        'ONSS_TYPE_OF_COMPANY', 
        'ORIGINE', 
        'OT24', 
        'OT24_YEAR', 
        'PARTICULAR_SITUATIONS_INPS_INAIL', 
        'PARTICULAR_SITUATIONS_INPS_INAIL_DETAIL', 
        'PAYROLL_MANAGEMENT', 
        'PAYROLL_OUTSOURCER', 
        'PAYROLL_SOFTWARE', 
        'PAYS', 
        'PERS_MORALE_OU_PERS_PHYSIQUE', 
        'PO_MANDATORY', 
        'RAISON_SOC', 
        'REAL_ECONOMIC_ACTIVITY', 
        'RECO_GROUP', 
        'REVENDEUR', 
        'SAVING_ACTIONS', 
        'SAVING_ACTIONS_OTHERS', 
        'SCORING_FINANCIER', 
        'SCORING_IT_1', 
        'SCORING_IT_2', 
        'SCORING_IT_3', 
        'SCORING_IT_4', 
        'SCORING_IT_5', 
        'SCORING_IT_6', 
        'SCORING_IT_7', 
        'SCORING_IT_8', 
        'SCORING_IT_9', 
        'SCORING_TOTAL', 
        'SECOND_LEVEL_CONTRACTS', 
        'SECRETARIAT_SOCIAL_ADRESSE', 
        'SECRETARIAT_SOCIAL_EMAIL', 
        'SECRETARIAT_SOCIAL_GESTIONNAIRE', 
        'SECRETARIAT_SOCIAL_NOM', 
        'SECRETARIAT_SOCIAL_TEL', 
        'SECTEUR_GEO', 
        'SEGMENT', 
        'SIRET', 
        'SIRET2', 
        'SIRET3', 
        'SITE_WEB', 
        'SITUATION_JURIDIQUE', 
        'SITUATION_JURIDIQUE_DATE', 
        'SOCIAL_CAPITAL', 
        'SPI_CERTIFICADO', 
        'SPI_SUBVENCIONES', 
        'SPLIT', 
        'SUB_SECTOR', 
        'SUIVI_PAR', 
        'SUIVI_PAR_MANUEL', 
        'SUIVI_PAR_REAFF', 
        'SYS_DATE_CREATION', 
        'SYS_DATE_MODIFICATION', 
        'SYS_HEURE_CREATION', 
        'SYS_HEURE_MODIFICATION', 
        'SYS_MAP_ADRESSE_GEOCODEE', 
        'SYS_MAP_LATITUDE', 
        'SYS_MAP_LONGITUDE', 
        'SYS_MAP_QUALITE_GEOCODAGE', 
        'SYS_SYNCHRO_CODE_POSTE', 
        'SYS_SYNCHRO_DATE_ENREG', 
        'SYS_USER_CREATION', 
        'SYS_USER_MODIFICATION', 
        'TARGET_AT', 
        'TARGET_JIB', 
        'TARGET_ONSS', 
        'TARGET_PRP', 
        'TARGET_PRP_CHANTIER', 
        'TARGET_SOCIAL', 
        'TELEPHONE', 
        'TGG_2017', 
        'TGG_2019', 
        'TOP_TARGET_AT', 
        'TOP_TARGET_PRP', 
        'TO_DELETE', 
        'TRANCHE_CA', 
        'TRANCHE_CA_2', 
        'TRANSFER_ABROAD', 
        'TRANSFER_ITALIA', 
        'TYPE_FICHE', 
        'URSSAF', 
        'URSSAF_MDP_NET_ENTREPRISE', 
        'URSSAF_NO_COTISANT1', 
        'URSSAF_NO_COTISANT2', 
        'URSSAF_RATTACHEMENT', 
        'URSSAF_VLU', 
        'VILLE', 
        'VOCE_TARIFFA_NOT_0722_0723', 
        'VP_N_SOCIETE', 
        'WORKFORCE_2_YEAR', 
        'WORKFORCE_YEAR', 
        'PARTNER_UPDATE_DATE', 
        'SINE', 
        'TOP_TARGET_INNO', 
        'TOP_TARGET_ONSS', 
        'UNIVERSITY_GRADUATES', 
        'WORKERS_BLUE_COLLAR', 
        'PAYROLL_OUTSOURCER_TYPE', 
        'TGG_2019_B', 
    ],
    // 'action_autres_contacts' => ['xxx'],
    'action_intervenants_fiabilis' => [
        'ID_ACTION_INTERVENANTS_FIABILIS', 
        'PID_ACTION', 
        'LOGIN', 
        'SYS_DATE_CREATION', 
        'SYS_DATE_MODIFICATION', 
        'SYS_HEURE_CREATION', 
        'SYS_HEURE_MODIFICATION', 
        'SYS_USER_CREATION', 
        'SYS_USER_MODIFICATION',
    ],
    // 'action_marketing',
    // 'adresses',
    'affaire' => [
        'ID_AFFAIRE',  
        'PID_CONCURRENT',  
        'PID_CONTACT',  
        'PID_CONTRAT',  
        'PID_IDENTIFICATION',  
        'BITRIX_KEY',  
        'CIVILITE',  
        'CONCURRENT',  
        'DATE_PERTE',  
        'DATE_PREVISIONNEL',  
        'DATE_SIGNATURE',  
        'EMAIL',  
        'FAMILLE',  
        'IT_COMPTEUR',  
        'MEMO',  
        'MONTANT_PONDERE',  
        'MOTIF_PERTE',  
        'NOM',  
        'NO_AFFAIRE',  
        'PHASE',  
        'PRENOM',  
        'PROBABILITE',  
        'PRODUIT',  
        'STATUT',  
        'SUIVI_PAR',  
        'SYS_DATE_CREATION',  
        'SYS_DATE_MODIFICATION',  
        'SYS_HEURE_CREATION',  
        'SYS_HEURE_MODIFICATION',  
        'SYS_SYNCHRO_CODE_POSTE',  
        'SYS_SYNCHRO_DATE_ENREG',  
        'SYS_USER_CREATION',  
        'SYS_USER_MODIFICATION',  
        'TOTAL_PREVISIONNEL',  
        'VP_N_AFFAIRE',  
        'VP_N_CONTRAT_CADRE',  
        'VP_N_CONTRAT_PARTIEL',  
        'INTERNATIONAL_SALES',  
    ],
    'affaire_conditions_financieres' => [
        'xxx',
    ],
    // 'affaire_intervenants',
    'affaire_objections' => [
        'ID_AFFAIRE_OBJECTIONS',
        'COMMENTS',
        'DATE',
        'OBJECTIONS',
        'PID_AFFAIRE',
        'SOLVED',
        'STEP',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_action_categorie' => [
        'ID_AIDE_ACTION_CATEGORIE',
        'CATEGORIE',
        'EXCLUSIVE',
        'GROUPE',
        'MISE_A_JOUR_AGENDA',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE_EVENEMENT',
    ],
    'aide_action_objet' => [
        'ID_AIDE_ACTION_OBJET',
        'CATEGORIE',
        'OBJET',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_action_origine' => [
        'ID_AIDE_ACTION_ORIGINE',
        'ORIGINE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_action_resultat' => [
        
    ],
    'aide_affaire_objections' => [
        
    ],
    'aide_affaire_perte' => [
        
    ],
    'aide_affaire_phase' => [
        
    ],
    // 'aide_affaire_probabilite' => ['xxx'],
    'aide_affaire_statut' => [
        
    ],
    'aide_affaire_year' => [
        
    ],
    'aide_article_famille' => [
        
    ],
    'aide_article_provider' => [
        
    ],
    // 'aide_article_sfamille' => ['xxx'],
    // 'aide_article_unite' => ['xxx'],
    // 'aide_book_categorie' => ['xxx'],
    'aide_contact_civilite' => [
        
    ],
    'aide_contact_fonction' => [
        
    ],
    'aide_contact_language' => [
        
    ],
    // 'aide_contact_mailing' => ['xxx'],
    'aide_contact_service' => [
        
    ],
    // 'aide_contact_target' => ['xxx'],
    'aide_contrat_entity' => [
        
    ],
    'aide_contrat_mode_signature' => [
        
    ],
    'aide_contrat_statut' => [
        
    ],
    'aide_contrat_type' => [
        
    ],
    'aide_contrat_type_reconduction' => [
        
    ],
    // 'aide_contrat_unite' => ['xxx'],
    // 'aide_events' => ['xxx'],
    'aide_events_qualification' => [
        
    ],
    'aide_events_status' => [
        
    ],
    'aide_famille_indicators' => [
        
    ],
    'aide_international_responsible' => [
        
    ],
    'aide_international_sector' => [
        
    ],
    // 'aide_invoice_libelle_fusion' => ['xxx'],
    // 'aide_mailing_categorie' => ['xxx'],
    // 'aide_mailing_lot' => ['xxx'],
    'aide_mission_motif' => [
        
    ],
    'aide_mission_sous_motif1' => [
        
    ],
    'aide_mission_sous_motif2' => [
        
    ],
    'aide_mission_step' => [
        
    ],
    // 'aide_notes_de_frais_cv' => ['xxx'],
    // 'aide_notes_de_frais_service_provider' => ['xxx'],
    // 'aide_notes_de_frais_type' => ['xxx'],
    'aide_offre_condition' => [
        
    ],
    // 'aide_offre_condition_libelle_fusion' => ['xxx'],
    // 'aide_raison_echantillon' => ['xxx'],
    // 'aide_reclamation_criticite' => ['xxx'],
    // 'aide_reclamation_origine' => ['xxx'],
    // 'aide_reclamation_statut' => ['xxx'],
    // 'aide_reclamation_type' => ['xxx'],
    'aide_renumeration_type' => [
        
    ],
    // 'aide_societe_activite' => ['xxx'],
    // 'aide_societe_broker' => ['xxx'],
    'aide_societe_ca' => [
        
    ],
    // 'aide_societe_ccnl' => ['xxx'],
    // 'aide_societe_certificado' => ['xxx'],
    // 'aide_societe_commission_paritaire' => ['xxx'],
    'aide_societe_commune' => [
        
    ],
    'aide_societe_company_classification' => [
        
    ],
    // 'aide_societe_convention_collective' => ['xxx'],
    // 'aide_societe_csc' => ['xxx'],
    // 'aide_societe_dpt' => ['xxx'],
    'aide_societe_effectif' => [
        
    ],
    'aide_societe_forme_juridique' => [
        
    ],
    // 'aide_societe_groupe' => ['xxx'],
    // 'aide_societe_insurance' => ['xxx'],
    'aide_societe_naf' => [
        
    ],
    // 'aide_societe_naf_csc' => ['xxx'],
    'aide_societe_origine' => [
        
    ],
    // 'aide_societe_payroll_outsourcer' => ['xxx'],
    'aide_societe_payroll_outsourcer_type' => [
        
    ],
    'aide_societe_pays' => [
        
    ],
    // 'aide_societe_region' => ['xxx'],
    // 'aide_societe_saving_actions' => ['xxx'],
    // 'aide_societe_secteur' => ['xxx'],
    'aide_societe_secteur_geo' => [
        
    ],
    'aide_societe_segment' => [
        
    ],
    'aide_societe_situation_juridique' => [
        
    ],
    'aide_societe_sub_sector_geo' => [
        
    ],
    'aide_societe_type' => [
        
    ],
    'aide_societe_typeadr' => [
        
    ],
    // 'aide_societe_urssaf' => ['xxx'],
    // 'aide_texte_memo' => ['xxx'],
    // 'aide_ticket_statut' => ['xxx'],
    // 'aide_ticket_type' => ['xxx'],
    'article' => [
        
    ],
    // 'articles_lies' => ['xxx'],
    // 'articles_photos' => ['xxx'],
    // 'base_connaissance' => ['xxx'],
    // 'base_connaissance_mot_cle' => ['xxx'],
    // 'book' => ['xxx'],
    // 'campagne' => ['xxx'],
    // 'concurrent' => ['xxx'],
    'contact' => [
        'ADRESSE1',
        'ADRESSE2',
        'ADRESSE3',
        'ADRESSE_SPECIFIQUE',
        'BITRIX_COMPANY',
        'BITRIX_KEY',
        'CFO_EVENT',
        'CIVILITE',
        'CODE_MAILING',
        'CODE_POSTAL',
        'CONTACT_PRINCIPAL',
        'CONTACT_PRINCIPAL_PROD',
        'DECIDEUR',
        'DESTINATAIRE_MAILING',
        'E_MAIL',
        'FACTURATION',
        'FAX_DIRECT',
        'FIABILIS_CONTACT',
        'FONCTION',
        'FONCTION_CV',
        'HR_EVENT',
        'ID_CONTACT',
        'IMPOSSIBLE_A_JOINDRE',
        'INACTIVE',
        'INTERNATIONAL_DECISION_MAKER',
        'JURISTE',
        'LANGUAGE',
        'LINKEDIN_URL_PUB',
        'MAIL_REJETE',
        'NE_PAS_CONTACTER_PHONING',
        'NE_PAS_ENVOYER_MAIL',
        'NE_PAS_ENVOYER_SMS',
        'NOM',
        'NOTE',
        'OK_SYNCHRO_EXCHANGE',
        'OPERATIONNEL',
        'OTHER_LANGUAGE_SPOKEN',
        'PAYS',
        'PID_IDENTIFICATION',
        'PRENOM',
        'PRESCRIPTEUR',
        'RAISON_SOCIALE',
        'SERVICE',
        'SIGNATAIRE',
        'SUIVI_PAR',
        'SYS_DATE_CREATION',
        'SYS_DATE_EXCHANGE',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_ID_EXCHANGE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TARGET',
        'TELEPHONE_DIRECT',
        'TELEPHONE_MOBILE',
        'TEMPO_VP',
        'VIADEO_URL_PUB',
        'VILLE',
        'VP_N_CONTACT',
    ],
    'contrat' => [

    ],
    'contrat_detail_produit' => [
        
    ],
    // 'contrat_fournisseur' => ['xxx'],
    // 'contrat_parc' => ['xxx'],
    'contrat_partiel_condition_fiancieres' => [
        
    ],
    // 'contrat_revue_annuelle' => ['xxx'],
    'documents' => [
        
    ],
    // 'echantillon' => ['xxx'],
    // 'echantillon_article' => ['xxx'],
    // 'email' => ['xxx'],
    // 'email_pj' => ['xxx'],
    // 'events' => ['xxx'],
    'historique_maj_affaire' => [
        
    ],
    'identification' => [
        'ID_IDENTIFICATION', 
        'PID_GROUP', 
        'PID_INTERNATIONAL_GROUP', 
        'PID_PARTNER', 
        'PID_REVENDEUR', 
        'PID_SUSPECTS', 
        'ACTIVITE', 
        'ACTIVITY_INAIL_CLASSIFICATION', 
        'ACTIVITY_INPS_CLASSIFICATION', 
        'ADRESSE1', 
        'ADRESSE2', 
        'ADRESSE3', 
        'AT_AO_BROKER', 
        'AT_AO_CONTRACT_ENDING_DATE', 
        'AT_AO_CONTRACT_STARTING_DATE', 
        'AT_AO_INSURANCE', 
        'AT_AO_POLICE_NBRE', 
        'AUDITEUR', 
        'BELSPO', 
        'BENEFITS', 
        'BITRIX_KEY', 
        'CA', 
        'CA_2', 
        'CA_2_ANNEE', 
        'CA_ANNEE', 
        'CCNL_MAIN', 
        'CCNL_SECONDARY', 
        'CLIENT_SECURE', 
        'CODE_CLIENT', 
        'CODE_NAF', 
        'CODE_NAF2', 
        'CODE_POSTAL', 
        'CODE_TVA_INTRA', 
        'COMPANY_CLASSIFICATION', 
        'COMPL_RAISON_SOC', 
        'CONVENTION_COLLECTIVE_IDCC', 
        'CONVENTION_COLLECTIVE_TITRE', 
        'CREATION_DATE', 
        'CSC_CODE_INPS_CLASSIFICATION', 
        'CSP_ETRANGER', 
        'CSP_FRANCE', 
        'CUSTOMER_RELATIONSHIP_MANAGER', 
        'DIGITAL_INVOICE_ONLY', 
        'DIGITAL_INVOICE_REFUSED', 
        'DMFA_REQUEST', 
        'EFFECTIF', 
        'EFFECTIF_2', 
        'EFFECTIF_NUM', 
        'EFFECTIF_NUM_2', 
        'EMAIL', 
        'EMPLOYEES_USE_CARS', 
        'EPISODES_OF_INTEGRATION_OR_SOLIDARITY', 
        'EPISODES_OF_INTEGRATION_OR_SOLIDARITY_YEAR', 
        'FAX', 
        'FISCAL_CLOSING', 
        'FORME_JURIDIQUE', 
        'FUSION', 
        'GROUP', 
        'HEAD_OFFICE', 
        'HEAD_OFFICE_NAME', 
        'INCORPORATION', 
        'INTERNATIONAL', 
        'INTERNATIONAL_COMPANY', 
        'INTERNATIONAL_GROUP', 
        'INTERNATIONAL_HEAD_OFFICE', 
        'INTERNATIONAL_HEAD_OFFICE_TYPE', 
        'INTERNATIONAL_RESPONSIBLE', 
        'INTERNATIONAL_SECTOR', 
        'INVOICE_LANGUAGE', 
        'IP_BELGIUM', 
        'IP_BRAZIL', 
        'IP_CHILE', 
        'IP_COUNTRY_OF_THE_DECISION_MAKER', 
        'IP_FRANCE', 
        'IP_GERMANY', 
        'IP_ITALY', 
        'IP_POLAND', 
        'IP_SPAIN', 
        'IWT', 
        'KEY_ACCOUNT', 
        'LIQUIDATION', 
        'LISTED_COMPANY', 
        'MAPS_ADRESSE', 
        'MAPS_ADRESSE_PHYSIQUE', 
        'MAPS_CODE_POSTAL', 
        'MAPS_PAYS', 
        'MAPS_VILLE', 
        'NB_ETABLISSEMENTS', 
        'NET_PROFIT', 
        'NOM_EXPEDITEUR', 
        'NUMBER_MANAGERS', 
        'N_CANAL_SFTP', 
        'ONSS_PROTOCOL', 
        'ONSS_TYPE_OF_COMPANY', 
        'ORIGINE', 
        'OT24', 
        'OT24_YEAR', 
        'PARTICULAR_SITUATIONS_INPS_INAIL', 
        'PARTICULAR_SITUATIONS_INPS_INAIL_DETAIL', 
        'PAYROLL_MANAGEMENT', 
        'PAYROLL_OUTSOURCER', 
        'PAYROLL_SOFTWARE', 
        'PAYS', 
        'PERS_MORALE_OU_PERS_PHYSIQUE', 
        'PO_MANDATORY', 
        'RAISON_SOC', 
        'REAL_ECONOMIC_ACTIVITY', 
        'RECO_GROUP', 
        'REVENDEUR', 
        'SAVING_ACTIONS', 
        'SAVING_ACTIONS_OTHERS', 
        'SCORING_FINANCIER', 
        'SCORING_IT_1', 
        'SCORING_IT_2', 
        'SCORING_IT_3', 
        'SCORING_IT_4', 
        'SCORING_IT_5', 
        'SCORING_IT_6', 
        'SCORING_IT_7', 
        'SCORING_IT_8', 
        'SCORING_IT_9', 
        'SCORING_TOTAL', 
        'SECOND_LEVEL_CONTRACTS', 
        'SECRETARIAT_SOCIAL_ADRESSE', 
        'SECRETARIAT_SOCIAL_EMAIL', 
        'SECRETARIAT_SOCIAL_GESTIONNAIRE', 
        'SECRETARIAT_SOCIAL_NOM', 
        'SECRETARIAT_SOCIAL_TEL', 
        'SECTEUR_GEO', 
        'SEGMENT', 
        'SIRET', 
        'SIRET2', 
        'SIRET3', 
        'SITE_WEB', 
        'SITUATION_JURIDIQUE', 
        'SITUATION_JURIDIQUE_DATE', 
        'SOCIAL_CAPITAL', 
        'SPI_CERTIFICADO', 
        'SPI_SUBVENCIONES', 
        'SPLIT', 
        'SUB_SECTOR', 
        'SUIVI_PAR', 
        'SUIVI_PAR_MANUEL', 
        'SUIVI_PAR_REAFF', 
        'SYS_DATE_CREATION', 
        'SYS_DATE_MODIFICATION', 
        'SYS_HEURE_CREATION', 
        'SYS_HEURE_MODIFICATION', 
        'SYS_MAP_ADRESSE_GEOCODEE', 
        'SYS_MAP_LATITUDE', 
        'SYS_MAP_LONGITUDE', 
        'SYS_MAP_QUALITE_GEOCODAGE', 
        'SYS_SYNCHRO_CODE_POSTE', 
        'SYS_SYNCHRO_DATE_ENREG', 
        'SYS_USER_CREATION', 
        'SYS_USER_MODIFICATION', 
        'TARGET_AT', 
        'TARGET_JIB', 
        'TARGET_ONSS', 
        'TARGET_PRP', 
        'TARGET_PRP_CHANTIER', 
        'TARGET_SOCIAL', 
        'TELEPHONE', 
        'TGG_2017', 
        'TGG_2019', 
        'TOP_TARGET_AT', 
        'TOP_TARGET_PRP', 
        'TO_DELETE', 
        'TRANCHE_CA', 
        'TRANCHE_CA_2', 
        'TRANSFER_ABROAD', 
        'TRANSFER_ITALIA', 
        'TYPE_FICHE', 
        'URSSAF', 
        'URSSAF_MDP_NET_ENTREPRISE', 
        'URSSAF_NO_COTISANT1', 
        'URSSAF_NO_COTISANT2', 
        'URSSAF_RATTACHEMENT', 
        'URSSAF_VLU', 
        'VILLE', 
        'VOCE_TARIFFA_NOT_0722_0723', 
        'VP_N_SOCIETE', 
        'WORKFORCE_2_YEAR', 
        'WORKFORCE_YEAR', 
        'PARTNER_UPDATE_DATE', 
        'SINE', 
        'TOP_TARGET_INNO', 
        'TOP_TARGET_ONSS', 
        'UNIVERSITY_GRADUATES', 
        'WORKERS_BLUE_COLLAR', 
        'PAYROLL_OUTSOURCER_TYPE', 
        'TGG_2019_B', 
    ],
    // 'identification_lies' => ['xxx'],
    'identification_note' => [
        
    ],
    // 'import' => ['xxx'],
    // 'import2' => ['xxx'],
    // 'import_famille_produit_step' => ['xxx'],
    // 'indicators' => ['xxx'],
    'invoice' => [
        
    ],
    'invoice_ligne' => [
        
    ],
    'journal_deleted' => [
        
    ],
    // 'journal_maj_champ' => ['xxx'],
    // 'lignes_factures' => ['xxx'],
    // 'lot' => ['xxx'],
    'mission' => [
        
    ],
    // 'mission_audit_report' => ['xxx'],
    // 'mission_cnae' => ['xxx'],
    'mission_motive' => [
        
    ],
    'mission_motive_eco' => [
        
    ],
    'mission_motive_historique_maj' => [
        
    ],
    // 'mission_sites' => ['xxx'],
    'mission_team' => [
        
    ],
    // 'modeles' => ['xxx'],
    'mydbr_reportgroups' => [
        
    ],
    'mydbr_folders' => [
        
    ],
    'mydbr_folders_priv' => [
        
    ],
    // 'mydbr_groups' => ['xxx'],
    // 'mydbr_groupsusers' => ['xxx'],
    // 'mydbr_key_column_usage' => ['xxx'],
    'mydbr_languages' => [
        
    ],
    'mydbr_licenses' => [
        
    ],
    'mydbr_param_queries' => [
        
    ],
    // 'mydbr_remote_servers' => ['xxx'],
    // 'mydbr_report_extensions' => ['xxx'],
    // 'mydbr_reports_priv' => ['xxx'],
    // 'mydbr_scheduled_tasks' => ['xxx'],
    'mydbr_snippets' => [
        
    ],
    // 'mydbr_statistics' => ['xxx'],
    'mydbr_styles' => [
        
    ],
    // 'mydbr_sync_exclude' => ['xxx'],
    'mydbr_template_folders' => [
        
    ],
    // 'mydbr_templates' => ['xxx'],
    // 'mydbr_ui_category_collapse' => ['xxx'],
    'mydbr_update' => [
        
    ],
    'mydbr_user_agents' => [
        
    ],
    // 'mydbr_user_logins' => ['xxx'],
    'mydbr_userlogin' => [
        
    ],
    'mydbr_version' => [
        
    ],
    // 'note_frais' => ['xxx'],
    // 'note_frais_detail' => ['xxx'],
    // 'note_frais_justificatif' => ['xxx'],
    // 'offre_detail' => ['xxx'],
    // 'offre_entete' => ['xxx'],
    // 'parc' => ['xxx'],
    // 'prepa_mailing' => ['xxx'],
    // 'reclamation' => ['xxx'],
    'settings' => [
        
    ],
    // 'sms' => ['xxx'],
    // 'societe_commission_paritaire' => ['xxx'],
    'societe_famille' => [
        
    ],
    // 'societe_subvenciones' => ['xxx'],
    // 'suspects' => ['xxx'],
    // 'sys_cube' => ['xxx'],
    // 'sys_droits_taches' => ['xxx'],
    // 'sys_droits_users' => ['xxx'],
    // 'sys_exchange_deleted' => ['xxx'],
    // 'sys_exchange_journal' => ['xxx'],
    // 'sys_filtrage_users' => ['xxx'],
    // 'sys_formulaire_personnalise' => ['xxx'],
    // 'sys_google_date_synchro' => ['xxx'],
    // 'sys_google_journal' => ['xxx'],
    'sys_groupes_users' => [
        
    ],
    'sys_histo_navigation' => [
        
    ],
    'sys_notifications' => [
        
    ],
    // 'sys_notifications_erreurs' => ['xxx'],
    // 'sys_planning_jours_indisponibles' => ['xxx'],
    'sys_requetes_memorisees' => [
        
    ],
    // 'sys_rgpd_bdd' => ['xxx'],
    // 'sys_rgpd_champs' => ['xxx'],
    // 'sys_rgpd_tables' => ['xxx'],
    // 'sys_synchro_deleted' => ['xxx'],
    // 'sys_synchro_journal' => ['xxx'],
    // 'sys_synchro_parametres' => ['xxx'],
    // 'sys_synchro_parametres_details' => ['xxx'],
    // 'sys_synchro_scripts_instructions' => ['xxx'],
    // 'sys_synchro_scripts_names' => ['xxx'],
    // 'sys_track_emailing' => ['xxx'],
    // 'sys_unsubscribed_emailing' => ['xxx'],
    'sys_users' => [
        
    ],
    'sys_users_connectes' => [
        
    ],
    'sys_users_connectes_historique' => [
        
    ],
    // 'sys_users_dependances' => ['xxx'],
    // 'ticket' => ['xxx'],
    // 'ticket_detail' => ['xxx'],
    // 'ticket_heures' => ['xxx'],
    // 'tliste_action_marketing' => ['xxx'],
    // 'tliste_actions' => ['xxx'],
    // 'tliste_societes' => ['xxx'],
    // 'tmp_eco' => ['xxx'],
];