<?php

return [ // LA TABLA CON SUS CAMPOS
    'action' => [
        'ID_ACTION', 
        'PID_AFFAIRE', 
        'PID_CONTACT', 
        'PID_CONTRAT', 
        'PID_IDENTIFICATION', 
        'PID_LOT', 
        'PID_MISSION', 
        'PID_OFFRE_ENTETE', 
        'PID_RECLAMATION', 
        'ALARME', 
        'BITRIX_CONTACT', 
        'BITRIX_KEY', 
        'CATEGORIE', 
        'CIVILITE', 
        'CODE_CAMPAGNE', 
        'DATE_ALARME', 
        'DATE_DEBUT', 
        'DATE_FIN', 
        'DUREE_CHRONO', 
        'EMPLACEMENT', 
        'E_MAIL', 
        'FAIT', 
        'HEURE_ALARME', 
        'HEURE_DEBUT', 
        'HEURE_FIN', 
        'NB_MINUTES_AVANT_ALARME', 
        'NOM', 
        'NOTE', 
        'NO_AFFAIRE', 
        'NO_CONTRAT', 
        'NO_LOT', 
        'NO_MISSION', 
        'NO_OFFRE', 
        'NO_RECLAMATION', 
        'OBJET', 
        'ORIGINE_ACTION', 
        'PRENOM', 
        'PRODUIT', 
        'RESULTAT', 
        'SUIVI_PAR', 
        'SYS_DATE_CREATION', 
        'SYS_DATE_EXCHANGE', 
        'SYS_DATE_MODIFICATION', 
        'SYS_HEURE_CREATION', 
        'SYS_HEURE_MODIFICATION', 
        'SYS_ID_EXCHANGE', 
        'SYS_SYNCHRO_CODE_POSTE', 
        'SYS_SYNCHRO_DATE_ENREG', 
        'SYS_USER_CREATION', 
        'SYS_USER_MODIFICATION', 
        'TYPE_EVENEMENT', 
        'VP_N_ACTION', 
        'VP_N_AFFAIRE', 
        'VP_N_CONTACT', 
    ],
    // 'action_autres_contacts' => ['xxx'],
    'action_intervenants_fiabilis' => [
        'ID_ACTION_INTERVENANTS_FIABILIS', 
        'PID_ACTION', 
        'LOGIN', 
        'SYS_DATE_CREATION', 
        'SYS_DATE_MODIFICATION', 
        'SYS_HEURE_CREATION', 
        'SYS_HEURE_MODIFICATION', 
        'SYS_USER_CREATION', 
        'SYS_USER_MODIFICATION',
    ],
    // 'action_marketing',
    // 'adresses',
    'affaire' => [
        'ID_AFFAIRE',  
        'PID_CONCURRENT',  
        'PID_CONTACT',  
        'PID_CONTRAT',  
        'PID_IDENTIFICATION',  
        'BITRIX_KEY',  
        'CIVILITE',  
        'CONCURRENT',  
        'DATE_PERTE',  
        'DATE_PREVISIONNEL',  
        'DATE_SIGNATURE',  
        'EMAIL',  
        'FAMILLE',  
        'IT_COMPTEUR',  
        'MEMO',  
        'MONTANT_PONDERE',  
        'MOTIF_PERTE',  
        'NOM',  
        'NO_AFFAIRE',  
        'PHASE',  
        'PRENOM',  
        'PROBABILITE',  
        'PRODUIT',  
        'STATUT',  
        'SUIVI_PAR',  
        'SYS_DATE_CREATION',  
        'SYS_DATE_MODIFICATION',  
        'SYS_HEURE_CREATION',  
        'SYS_HEURE_MODIFICATION',  
        'SYS_SYNCHRO_CODE_POSTE',  
        'SYS_SYNCHRO_DATE_ENREG',  
        'SYS_USER_CREATION',  
        'SYS_USER_MODIFICATION',  
        'TOTAL_PREVISIONNEL',  
        'VP_N_AFFAIRE',  
        'VP_N_CONTRAT_CADRE',  
        'VP_N_CONTRAT_PARTIEL',  
        'INTERNATIONAL_SALES',  
    ],
    'affaire_conditions_financieres' => [
        'ID_AFFAIRE_CONDITIONS_FINANCIERES',
        'PID_AFFAIRE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE',
        'VALEUR',
        'YEAR',
    ],
    // 'affaire_intervenants',
    'affaire_objections' => [
        'ID_AFFAIRE_OBJECTIONS',
        'PID_AFFAIRE',
        'COMMENTS',
        'DATE',
        'OBJECTIONS',
        'SOLVED',
        'STEP',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_action_categorie' => [
        'ID_AIDE_ACTION_CATEGORIE',
        'CATEGORIE',
        'EXCLUSIVE',
        'GROUPE',
        'MISE_A_JOUR_AGENDA',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE_EVENEMENT',
    ],
    'aide_action_objet' => [
        'ID_AIDE_ACTION_OBJET',
        'CATEGORIE',
        'OBJET',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_action_origine' => [
        'ID_AIDE_ACTION_ORIGINE',
        'ORIGINE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_action_resultat' => [
        'ID_AIDE_ACTION_RESULTAT',
        'CATEGORIE',
        'RESULTAT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_affaire_objections' => [
        'ID_AIDE_AFFAIRE_OBJECTIONS',
        'OBJECTIONS',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_affaire_perte' => [
        'ID_AIDE_AFFAIRE_PERTE',
        'MOTIF_PERTE',
        'NO_GO',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_affaire_phase' => [
        'ID_AIDE_AFFAIRE_PHASE',
        'PHASE',
        'PROBABILITE',
        'STATUT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_affaire_probabilite' => ['xxx'],
    'aide_affaire_statut' => [
        'ID_AIDE_AFFAIRE_STATUT',
        'STATUT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_affaire_year' => [
        'ID_AIDE_AFFAIRE_YEAR',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'VALUE',
    ],
    'aide_article_famille' => [
        'ID_AIDE_ARTICLE_FAMILLE',
        'CODE_ANALYTIQUE_SAGE',
        'FAMILLE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_article_provider' => [
        'ID_AIDE_ARTICLE_PROVIDER',
        'PROVIDER',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_article_sfamille' => ['xxx'],
    // 'aide_article_unite' => ['xxx'],
    // 'aide_book_categorie' => ['xxx'],
    'aide_contact_civilite' => [
        'ID_AIDE_CONTACT_CIVILITE',
        'CIVILITE',
        'LIBELLE',
        'PREFIX',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_contact_fonction' => [
        'ID_AIDE_CONTACT_FONCTION',
        'FONCTION',
        'SERVICE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_contact_language' => [
        'ID_AIDE_CONTACT_LANGUAGE',
        'CODE',
        'LANGUAGE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_contact_mailing' => ['xxx'],
    'aide_contact_service' => [
        'ID_AIDE_CONTACT_SERVICE',
        'SERVICE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_contact_target' => ['xxx'],
    'aide_contrat_entity' => [
        'ID_AIDE_CONTRAT_ENTITY',
        'IBAN',
        'INITIALS',
        'NAME',
        'NB_ANNEE_A_SOUSTRAIRE',
        'PREFIX_COMPTEUR',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'VALEUR_COMPTEUR_CREDIT_NOTE',
        'VALEUR_COMPTEUR_INVOICE',
    ],
    'aide_contrat_mode_signature' => [
        'ID_AIDE_CONTRAT_MODE_SIGNATURE',
        'MODE_SIGNATURE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_contrat_statut' => [
        'ID_AIDE_CONTRAT_STATUT',
        'STATUT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_contrat_type' => [
        'ID_AIDE_CONTRAT_TYPE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE',
    ],
    'aide_contrat_type_reconduction' => [
        'ID_AIDE_CONTRAT_TYPE_RECONDUCTION',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE_RECONDUCTION',
    ],
    // 'aide_contrat_unite' => ['xxx'],
    // 'aide_events' => ['xxx'],
    'aide_events_qualification' => [
        'ID_AIDE_EVENTS_QUALIFICATION',
        'QUALIFICATION',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_events_status' => [
        'ID_AIDE_EVENTS_STATUS',
        'STATUS',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_famille_indicators' => [
        'ID_AIDE_FAMILLE_INDICATORS',
        'FAMILLE',
        'INDICATORS',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'THRESHOLD',
    ],
    'aide_international_responsible' => [
        'ID_AIDE_INTERNATIONAL_RESPONSIBLE',
        'CODE',
        'NOM',
        'PAYS',
        'SERVICE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_international_sector' => [
        'ID_AIDE_INTERNATIONAL_SECTOR',
        'DETAIL',
        'SECTOR',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_invoice_libelle_fusion' => ['xxx'],
    // 'aide_mailing_categorie' => ['xxx'],
    // 'aide_mailing_lot' => ['xxx'],
    'aide_mission_motif' => [
        'ID_AIDE_MISSION_MOTIF',
        'FAMILLE',
        'MOTIF',
        'PRODUIT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_mission_sous_motif1' => [
        'ID_AIDE_MISSION_SOUS_MOTIF1',
        'SOUS_MOTIF',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_mission_sous_motif2' => [
        'ID_AIDE_MISSION_SOUS_MOTIF2',
        'SOUS_MOTIF',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_mission_step' => [
        'ID_AIDE_MISSION_STEP',
        'PID_AIDE_MISSION_MOTIF',
        'DUREE',
        'ETAPE',
        'FAMILLE',
        'MOTIF',
        'POURCENTAGE',
        'PRODUIT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TO_AUDIT',
    ],
    // 'aide_notes_de_frais_cv' => ['xxx'],
    // 'aide_notes_de_frais_service_provider' => ['xxx'],
    // 'aide_notes_de_frais_type' => ['xxx'],
    'aide_offre_condition' => [
        'ID_AIDE_OFFRE_CONDITION',
        'CONDITION',
        'FIN_DE_MOIS',
        'NB_JOURS',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_offre_condition_libelle_fusion' => ['xxx'],
    // 'aide_raison_echantillon' => ['xxx'],
    // 'aide_reclamation_criticite' => ['xxx'],
    // 'aide_reclamation_origine' => ['xxx'],
    // 'aide_reclamation_statut' => ['xxx'],
    // 'aide_reclamation_type' => ['xxx'],
    'aide_renumeration_type' => [
        'ID_AIDE_RENUMERATION_TYPE',
        'RENUMERATION_TYPE',
        'SYMBOLE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_societe_activite' => ['xxx'],
    // 'aide_societe_broker' => ['xxx'],
    'aide_societe_ca' => [
        'ID_AIDE_SOCIETE_CA',
        'CA_MAX',
        'CA_MIN',
        'CA_TRANCHE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_societe_ccnl' => ['xxx'],
    // 'aide_societe_certificado' => ['xxx'],
    // 'aide_societe_commission_paritaire' => ['xxx'],
    'aide_societe_commune' => [
        'ID_AIDE_SOCIETE_COMMUNE',
        'CODE_POSTAL',
        'COMMUNE',
        'INSEE',
        'LANGUE',
        'LIB_DEPARTEMENT',
        'NUM_DEPARTEMENT',
        'PAYS',
        'REGION',
        'SECTEUR',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_societe_company_classification' => [
        'ID_AIDE_SOCIETE_COMPANY_CLASSIFICATION',
        'COMPANY_CLASSIFICATION',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_societe_convention_collective' => ['xxx'],
    // 'aide_societe_csc' => ['xxx'],
    // 'aide_societe_dpt' => ['xxx'],
    'aide_societe_effectif' => [
        'ID_AIDE_SOCIETE_EFFECTIF',
        'EFFECTIF',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TRANCHE_MAXI',
        'TRANCHE_MINI',
    ],
    'aide_societe_forme_juridique' => [
        'ID_AIDE_SOCIETE_FORME_JURIDIQUE',
        'FORME_JURIDIQUE',
        'SIGLE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_societe_groupe' => ['xxx'],
    // 'aide_societe_insurance' => ['xxx'],
    'aide_societe_naf' => [
        'ID_AIDE_SOCIETE_NAF',
        'CODE',
        'IT_PART_TIME',
        'LIBELLE',
        'SEGMENT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TARGET_AT',
        'TARGET_INNO',
        'TARGET_ONSS',
        'TARGET_PRP',
        'TARGET_SOCIAL',
        'TGG_2017',
    ],
    // 'aide_societe_naf_csc' => ['xxx'],
    'aide_societe_origine' => [
        'ID_AIDE_SOCIETE_ORIGINE',
        'ORIGINE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_societe_payroll_outsourcer' => ['xxx'],
    'aide_societe_payroll_outsourcer_type' => [
        'ID_AIDE_SOCIETE_PAYROLL_OUTSOURCER_TYPE',
        'PAYROLL_OUTSOURCER_TYPE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_societe_pays' => [
        'ID_AIDE_SOCIETE_PAYS',
        'CODE_ISO',
        'CONTINENT',
        'INDICATIF_TEL',
        'INTERNATIONAL_POTENTIAL_EMAIL',
        'LATITUDE',
        'LONGITUDE',
        'NOM_PAYS',
        'NOM_PAYS_MAJ',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'aide_societe_region' => ['xxx'],
    // 'aide_societe_saving_actions' => ['xxx'],
    // 'aide_societe_secteur' => ['xxx'],
    'aide_societe_secteur_geo' => [
        'ID_AIDE_SOCIETE_SECTEUR_GEO',
        'SECTEUR_GEO',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_societe_segment' => [
        'ID_AIDE_SOCIETE_SEGMENT',
        'SEGMENT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_societe_situation_juridique' => [
        'ID_AIDE_SOCIETE_SITUATION_JURIDIQUE',
        'NIVEAU',
        'SITUATION_JURIDIQUE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_societe_sub_sector_geo' => [
        'ID_AIDE_SOCIETE_SUB_SECTOR_GEO',
        'SUB_SECTOR',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'aide_societe_type' => [
        'ID_AIDE_SOCIETE_TYPE',
        'NIVEAU',
        'PARTNER',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE_FICHE',
        'SUPPLIER',
    ],
    'aide_societe_typeadr' => [
        'ID_AIDE_SOCIETE_TYPEADR',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_NO_LIGNE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE_ADRESSE',
    ],
    // 'aide_societe_urssaf' => ['xxx'],
    // 'aide_texte_memo' => ['xxx'],
    // 'aide_ticket_statut' => ['xxx'],
    // 'aide_ticket_type' => ['xxx'],
    'article' => [
        'ID_ARTICLE',
        'CODE',
        'DESCRIPTIF',
        'DESIGNATION',
        'FAMILLE',
        'PHOTO_PRINCIPALE_FICHIER_CONTENU',
        'PHOTO_PRINCIPALE_FICHIER_DATE',
        'PHOTO_PRINCIPALE_FICHIER_NOM',
        'PHOTO_PRINCIPALE_FICHIER_TAILLE',
        'PHOTO_PRINCIPALE_FICHIER_TYPE',
        'PHOTO_PRINCIPALE_VIGNETTE_FICHIER_CONTENU',
        'PHOTO_PRINCIPALE_VIGNETTE_FICHIER_DATE',
        'PHOTO_PRINCIPALE_VIGNETTE_FICHIER_NOM',
        'PHOTO_PRINCIPALE_VIGNETTE_FICHIER_TAILLE',
        'PHOTO_PRINCIPALE_VIGNETTE_FICHIER_TYPE',
        'PRIX_ACHAT',
        'PRIX_VENTE',
        'SOUS_FAMILLE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE_LIAISON',
        'UNITE_FAC',
    ],
    // 'articles_lies' => ['xxx'],
    // 'articles_photos' => ['xxx'],
    // 'base_connaissance' => ['xxx'],
    // 'base_connaissance_mot_cle' => ['xxx'],
    // 'book' => ['xxx'],
    // 'campagne' => ['xxx'],
    // 'concurrent' => ['xxx'],
    'contact' => [
        'ID_CONTACT',
        'PID_IDENTIFICATION',
        'ADRESSE1',
        'ADRESSE2',
        'ADRESSE3',
        'ADRESSE_SPECIFIQUE',
        'BITRIX_COMPANY',
        'BITRIX_KEY',
        'CFO_EVENT',
        'CIVILITE',
        'CODE_MAILING',
        'CODE_POSTAL',
        'CONTACT_PRINCIPAL',
        'CONTACT_PRINCIPAL_PROD',
        'DECIDEUR',
        'DESTINATAIRE_MAILING',
        'E_MAIL',
        'FACTURATION',
        'FAX_DIRECT',
        'FIABILIS_CONTACT',
        'FONCTION',
        'FONCTION_CV',
        'HR_EVENT',
        'IMPOSSIBLE_A_JOINDRE',
        'INACTIVE',
        'INTERNATIONAL_DECISION_MAKER',
        'JURISTE',
        'LANGUAGE',
        'LINKEDIN_URL_PUB',
        'MAIL_REJETE',
        'NE_PAS_CONTACTER_PHONING',
        'NE_PAS_ENVOYER_MAIL',
        'NE_PAS_ENVOYER_SMS',
        'NOM',
        'NOTE',
        'OK_SYNCHRO_EXCHANGE',
        'OPERATIONNEL',
        'OTHER_LANGUAGE_SPOKEN',
        'PAYS',
        'PRENOM',
        'PRESCRIPTEUR',
        'RAISON_SOCIALE',
        'SERVICE',
        'SIGNATAIRE',
        'SUIVI_PAR',
        'SYS_DATE_CREATION',
        'SYS_DATE_EXCHANGE',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_ID_EXCHANGE',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TARGET',
        'TELEPHONE_DIRECT',
        'TELEPHONE_MOBILE',
        'TEMPO_VP',
        'VIADEO_URL_PUB',
        'VILLE',
        'VP_N_CONTACT',
    ],
    'contrat' => [
        'ID_CONTRAT',  
        'PID_AIDE_OFFRE_CONDITION',  
        'PID_CONTACT',  
        'PID_CONTACT_FACTURATION',  
        'PID_IDENTIFICATION',  
        'PID_PARTNER',  
        'ALERTE_FIN_CONTRAT',  
        'ALERTE_POSEE',  
        'CIVILITE',  
        'CIVILITE_FACTURATION',  
        'COMMENTAIRE',  
        'CONTRAT_TYPE',  
        'DATE_DEBUT_ANALYSE',  
        'DATE_DEBUT_CONTRAT',  
        'DATE_FIN_ANALYSE',  
        'DATE_FIN_CONTRAT',  
        'DATE_SIGNATURE_CLIENT',  
        'DATE_SIGNATURE_INTERNE',  
        'DROIT_DE_CITER',  
        'ENGAGEMENT_MOIS',  
        'E_MAIL',  
        'E_MAIL_FACTURATION',  
        'FAMILLE',  
        'FEE_INCLUDES_VAT',  
        'FIABILIS_GROUP_ENTITY',  
        'GROUPE',  
        'IT_COMPTEUR',  
        'MODE_SIGNATURE',  
        'MULTI_COMPANY_INVOICING',  
        'MULTI_ENTITY',  
        'MULTI_SALES',  
        'NOM',  
        'NOM_FACTURATION',  
        'NO_CONTRAT',  
        'NO_CONTRAT_ORIGINE',  
        'NO_ENTITY',  
        'NO_SUFFIXE',  
        'PRENOM',  
        'PRENOM_FACTURATION',  
        'RECONDUCTION_TYPE',  
        'STATUT',  
        'SUIVI_PAR',  
        'SYS_DATE_CREATION',  
        'SYS_DATE_MODIFICATION',  
        'SYS_HEURE_CREATION',  
        'SYS_HEURE_MODIFICATION',  
        'SYS_SYNCHRO_CODE_POSTE',  
        'SYS_SYNCHRO_DATE_ENREG',  
        'SYS_USER_CREATION',  
        'SYS_USER_MODIFICATION',  
        'TEMPO_VP',  
        'VALEUR',  
        'VP_NO_CONTRAT',  
        'INTERNATIONAL_SALES',  
    ],
    'contrat_detail_produit' => [
        'ID_CONTRAT_DETAIL_PRODUIT',
        'PID_CONTRAT',
        'PID_IDENTIFICATION',
        'DUPLICATION_CONTRAT_ID',
        'NO_CONTRAT_PARTIEL',
        'PRODUIT',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'VP_NO_CONTRAT',
    ],
    // 'contrat_fournisseur' => ['xxx'],
    // 'contrat_parc' => ['xxx'],
    'contrat_partiel_condition_fiancieres' => [
        'ID_CONTRAT_PARTIEL_CONDITION_FIANCIERES',
        'PID_CONTRAT',
        'PID_CONTRAT_DETAIL_PRODUIT',
        'COMMENTS',
        'REMUNERATION',
        'SENS',
        'SEUIL_MAX',
        'SEUIL_MIN',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'VALEUR',
        'YEAR',
    ],
    // 'contrat_revue_annuelle' => ['xxx'],
    'documents' => [
        'ID_DOCUMENTS',
        'PID_ACTION',
        'PID_AFFAIRE',
        'PID_CONTACT',
        'PID_CONTRAT',
        'PID_ECHANTILLON',
        'PID_EMAIL',
        'PID_IDENTIFICATION',
        'PID_INVOICE',
        'PID_MISSION',
        'PID_MISSION_AUDIT_REPORT',
        'PID_OFFRE_ENTETE',
        'PID_RECLAMATION',
        'ARCHIVE',
        'DOCUMENT_FICHIER_CONTENU',
        'DOCUMENT_FICHIER_DATE',
        'DOCUMENT_FICHIER_NOM',
        'DOCUMENT_FICHIER_TAILLE',
        'DOCUMENT_FICHIER_TYPE',
        'ORIGINE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TEMPO_VP',
        'PID_CONTRAT_FOURNISSEUR',
    ],
    // 'echantillon' => ['xxx'],
    // 'echantillon_article' => ['xxx'],
    // 'email' => ['xxx'],
    // 'email_pj' => ['xxx'],
    // 'events' => ['xxx'],
    'historique_maj_affaire' => [
        'ID_HISTORIQUE_MAJ_AFFAIRE',
        'PID_AFFAIRE',
        'ANCIENNE_VALEUR',
        'ANCIENNE_VALEUR_LIBELLE',
        'CHAMPS',
        'DATE',
        'NOUVELLE_VALEUR',
        'NOUVELLE_VALEUR_LIBELLE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'USER',
    ],
    'identification' => [
        'ID_IDENTIFICATION', 
        'PID_GROUP', 
        'PID_INTERNATIONAL_GROUP', 
        'PID_PARTNER', 
        'PID_REVENDEUR', 
        'PID_SUSPECTS', 
        'ACTIVITE', 
        'ACTIVITY_INAIL_CLASSIFICATION', 
        'ACTIVITY_INPS_CLASSIFICATION', 
        'ADRESSE1', 
        'ADRESSE2', 
        'ADRESSE3', 
        'AT_AO_BROKER', 
        'AT_AO_CONTRACT_ENDING_DATE', 
        'AT_AO_CONTRACT_STARTING_DATE', 
        'AT_AO_INSURANCE', 
        'AT_AO_POLICE_NBRE', 
        'AUDITEUR', 
        'BELSPO', 
        'BENEFITS', 
        'BITRIX_KEY', 
        'CA', 
        'CA_2', 
        'CA_2_ANNEE', 
        'CA_ANNEE', 
        'CCNL_MAIN', 
        'CCNL_SECONDARY', 
        'CLIENT_SECURE', 
        'CODE_CLIENT', 
        'CODE_NAF', 
        'CODE_NAF2', 
        'CODE_POSTAL', 
        'CODE_TVA_INTRA', 
        'COMPANY_CLASSIFICATION', 
        'COMPL_RAISON_SOC', 
        'CONVENTION_COLLECTIVE_IDCC', 
        'CONVENTION_COLLECTIVE_TITRE', 
        'CREATION_DATE', 
        'CSC_CODE_INPS_CLASSIFICATION', 
        'CSP_ETRANGER', 
        'CSP_FRANCE', 
        'CUSTOMER_RELATIONSHIP_MANAGER', 
        'DIGITAL_INVOICE_ONLY', 
        'DIGITAL_INVOICE_REFUSED', 
        'DMFA_REQUEST', 
        'EFFECTIF', 
        'EFFECTIF_2', 
        'EFFECTIF_NUM', 
        'EFFECTIF_NUM_2', 
        'EMAIL', 
        'EMPLOYEES_USE_CARS', 
        'EPISODES_OF_INTEGRATION_OR_SOLIDARITY', 
        'EPISODES_OF_INTEGRATION_OR_SOLIDARITY_YEAR', 
        'FAX', 
        'FISCAL_CLOSING', 
        'FORME_JURIDIQUE', 
        'FUSION', 
        'GROUP', 
        'HEAD_OFFICE', 
        'HEAD_OFFICE_NAME', 
        'INCORPORATION', 
        'INTERNATIONAL', 
        'INTERNATIONAL_COMPANY', 
        'INTERNATIONAL_GROUP', 
        'INTERNATIONAL_HEAD_OFFICE', 
        'INTERNATIONAL_HEAD_OFFICE_TYPE', 
        'INTERNATIONAL_RESPONSIBLE', 
        'INTERNATIONAL_SECTOR', 
        'INVOICE_LANGUAGE', 
        'IP_BELGIUM', 
        'IP_BRAZIL', 
        'IP_CHILE', 
        'IP_COUNTRY_OF_THE_DECISION_MAKER', 
        'IP_FRANCE', 
        'IP_GERMANY', 
        'IP_ITALY', 
        'IP_POLAND', 
        'IP_SPAIN', 
        'IWT', 
        'KEY_ACCOUNT', 
        'LIQUIDATION', 
        'LISTED_COMPANY', 
        'MAPS_ADRESSE', 
        'MAPS_ADRESSE_PHYSIQUE', 
        'MAPS_CODE_POSTAL', 
        'MAPS_PAYS', 
        'MAPS_VILLE', 
        'NB_ETABLISSEMENTS', 
        'NET_PROFIT', 
        'NOM_EXPEDITEUR', 
        'NUMBER_MANAGERS', 
        'N_CANAL_SFTP', 
        'ONSS_PROTOCOL', 
        'ONSS_TYPE_OF_COMPANY', 
        'ORIGINE', 
        'OT24', 
        'OT24_YEAR', 
        'PARTICULAR_SITUATIONS_INPS_INAIL', 
        'PARTICULAR_SITUATIONS_INPS_INAIL_DETAIL', 
        'PAYROLL_MANAGEMENT', 
        'PAYROLL_OUTSOURCER', 
        'PAYROLL_SOFTWARE', 
        'PAYS', 
        'PERS_MORALE_OU_PERS_PHYSIQUE', 
        'PO_MANDATORY', 
        'RAISON_SOC', 
        'REAL_ECONOMIC_ACTIVITY', 
        'RECO_GROUP', 
        'REVENDEUR', 
        'SAVING_ACTIONS', 
        'SAVING_ACTIONS_OTHERS', 
        'SCORING_FINANCIER', 
        'SCORING_IT_1', 
        'SCORING_IT_2', 
        'SCORING_IT_3', 
        'SCORING_IT_4', 
        'SCORING_IT_5', 
        'SCORING_IT_6', 
        'SCORING_IT_7', 
        'SCORING_IT_8', 
        'SCORING_IT_9', 
        'SCORING_TOTAL', 
        'SECOND_LEVEL_CONTRACTS', 
        'SECRETARIAT_SOCIAL_ADRESSE', 
        'SECRETARIAT_SOCIAL_EMAIL', 
        'SECRETARIAT_SOCIAL_GESTIONNAIRE', 
        'SECRETARIAT_SOCIAL_NOM', 
        'SECRETARIAT_SOCIAL_TEL', 
        'SECTEUR_GEO', 
        'SEGMENT', 
        'SIRET', 
        'SIRET2', 
        'SIRET3', 
        'SITE_WEB', 
        'SITUATION_JURIDIQUE', 
        'SITUATION_JURIDIQUE_DATE', 
        'SOCIAL_CAPITAL', 
        'SPI_CERTIFICADO', 
        'SPI_SUBVENCIONES', 
        'SPLIT', 
        'SUB_SECTOR', 
        'SUIVI_PAR', 
        'SUIVI_PAR_MANUEL', 
        'SUIVI_PAR_REAFF', 
        'SYS_DATE_CREATION', 
        'SYS_DATE_MODIFICATION', 
        'SYS_HEURE_CREATION', 
        'SYS_HEURE_MODIFICATION', 
        'SYS_MAP_ADRESSE_GEOCODEE', 
        'SYS_MAP_LATITUDE', 
        'SYS_MAP_LONGITUDE', 
        'SYS_MAP_QUALITE_GEOCODAGE', 
        'SYS_SYNCHRO_CODE_POSTE', 
        'SYS_SYNCHRO_DATE_ENREG', 
        'SYS_USER_CREATION', 
        'SYS_USER_MODIFICATION', 
        'TARGET_AT', 
        'TARGET_JIB', 
        'TARGET_ONSS', 
        'TARGET_PRP', 
        'TARGET_PRP_CHANTIER', 
        'TARGET_SOCIAL', 
        'TELEPHONE', 
        'TGG_2017', 
        'TGG_2019', 
        'TOP_TARGET_AT', 
        'TOP_TARGET_PRP', 
        'TO_DELETE', 
        'TRANCHE_CA', 
        'TRANCHE_CA_2', 
        'TRANSFER_ABROAD', 
        'TRANSFER_ITALIA', 
        'TYPE_FICHE', 
        'URSSAF', 
        'URSSAF_MDP_NET_ENTREPRISE', 
        'URSSAF_NO_COTISANT1', 
        'URSSAF_NO_COTISANT2', 
        'URSSAF_RATTACHEMENT', 
        'URSSAF_VLU', 
        'VILLE', 
        'VOCE_TARIFFA_NOT_0722_0723', 
        'VP_N_SOCIETE', 
        'WORKFORCE_2_YEAR', 
        'WORKFORCE_YEAR', 
        'PARTNER_UPDATE_DATE', 
        'SINE', 
        'TOP_TARGET_INNO', 
        'TOP_TARGET_ONSS', 
        'UNIVERSITY_GRADUATES', 
        'WORKERS_BLUE_COLLAR', 
        'PAYROLL_OUTSOURCER_TYPE', 
        'TGG_2019_B', 
    ],
    // 'identification_lies' => ['xxx'],
    'identification_note' => [
        'ID_IDENTIFICATION_NOTE',
        'PID_IDENTIFICATION',
        'KOMPASS_ID',
        'NOTE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'import' => ['xxx'],
    // 'import2' => ['xxx'],
    // 'import_famille_produit_step' => ['xxx'],
    // 'indicators' => ['xxx'],
    'invoice' => [
        'ID_INVOICE',
        'PID_CONTRAT',
        'PID_IDENTIFICATION',
        'PID_INVOICE',
        'CONTRACT_NBER',
        'DATE_EXPORT_SAGE',
        'DUE_DATE',
        'ENTITY_NBER',
        'FIABILIS_GROUP_ENTITY',
        'INVOICE_DATE',
        'INVOICE_NBER',
        'NO_CONTRAT',
        'PAYE',
        'PAYMENT_DATE',
        'PO',
        'PRODUCT',
        'SELECTION_EXPORT',
        'STATUS',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TOTAL_AMOUNT_INVOICED',
        'TYPE',
        'BALANCE_DUE',
        'NOM_MODELE_WORD',
    ],
    'invoice_ligne' => [
        'ID_INVOICE_LIGNE',
        'PID_INVOICE',
        'PID_INVOICE_LIGNE',
        'PID_MISSION_MOTIVE_ECO',
        'AMOUNT',
        'CN_CHOICE',
        'CN_ESTIMATED_DATE',
        'COMMENTAIRE',
        'DISPLAY_NEW_FEE',
        'ECO_AMOUNT',
        'FEES',
        'FEE_INCLUDES_VAT',
        'MOTIVE',
        'NO_LIGNE',
        'PRODUCT',
        'SUB_MOTIVE1',
        'SUB_MOTIVE2',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE',
        'YEAR',
    ],
    'journal_deleted' => [
        'ID_JOURNAL_DELETED',
        'INFORMATION',
        'RECORD_KEY',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TABLE',
    ],
    // 'journal_maj_champ' => ['xxx'],
    // 'lignes_factures' => ['xxx'],
    // 'lot' => ['xxx'],
    'mission' => [
        'ID_MISSION',
        'PID_CONTRAT',
        'PID_CONTRAT_DETAIL_PRODUIT',
        'PID_IDENTIFICATION',
        'COORDINATOR',
        'CURRENT_STEP',
        'DATE_DEBUT',
        'DATE_DEBUT_ANALYSE',
        'DATE_FIN_ANALYSE',
        'DATE_FIN_MISSION',
        'DEADLINE',
        'FAMILLE',
        'NO_CONTRAT',
        'NO_MISSION',
        'POURCENTAGE',
        'PRIORITY',
        'PRODUIT',
        'PROJECT_MANAGER',
        'STEPS_MANAGED_FROM_MOTIVE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'VP_FEES',
        'VP_N_CONTRAT_CADRE',
        'VP_N_CONTRAT_PARTIEL',
        'VP_PRODUCT',
    ],
    // 'mission_audit_report' => ['xxx'],
    // 'mission_cnae' => ['xxx'],
    'mission_motive' => [
        'ID_MISSION_MOTIVE',
        'PID_MISSION',
        'COMMENTS_SITE',
        'CONSULTANT',
        'DATE_LIMITE',
        'ETAPE_COURANTE',
        'MOTIF',
        'POURCENTAGE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    'mission_motive_eco' => [
        'ID_MISSION_MOTIVE_ECO',
        'PID_MISSION_MOTIVE',
        'DATE_PREVISIONNELLE',
        'ECO_ABANDONNEE',
        'ECO_A_FACTURER',
        'ECO_ECART',
        'ECO_PRESENTEE',
        'ECO_VALIDEE',
        'NOTES',
        'PACKAGE',
        'SELECTION_ECO_A_FACTURER',
        'SELECTION_ECO_VALIDEE',
        'SELECTION_FACTURATION',
        'SOUS_MOTIF_1',
        'SOUS_MOTIF_1_FROM_MONTH',
        'SOUS_MOTIF_1_FROM_YEAR',
        'SOUS_MOTIF_1_TO_MONTH',
        'SOUS_MOTIF_1_TO_YEAR',
        'SOUS_MOTIF_2',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TMP_NO_INVOICE',
        'YEAR',
        'CRITICITY',
        'TIME',
    ],
    'mission_motive_historique_maj' => [
        'ID_MISSION_MOTIVE_HISTORIQUE_MAJ',
        'PID_MISSION',
        'PID_MISSION_MOTIVE',
        'ANCIENNE_VALEUR',
        'ANCIENNE_VALEUR_LIBELLE',
        'CHAMPS',
        'DATE',
        'NOUVELLE_VALEUR',
        'NOUVELLE_VALEUR_LIBELLE',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'mission_sites' => ['xxx'],
    'mission_team' => [
        'ID_MISSION_TEAM',
        'PID_IDENTIFICATION',
        'PID_MISSION',
        'ACTIF',
        'CONSULTANT',
        'DATE_DEBUT',
        'DATE_FIN',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
    ],
    // 'modeles' => ['xxx'],
    'mydbr_reportgroups' => [
        'id',
        'name',
        'sortorder',
        'color',
    ],
    'mydbr_folders' => [
        'folder_id',
        'mother_id',
        'name',
        'invisible',
        'reportgroup',
        'explanation',
        'icon',
    ],
    'mydbr_folders_priv' => [
        'id',
        'folder_id',
        'username',
        'group_id',
        'authentication',
        'organization_id',
    ],
    // 'mydbr_groups' => ['xxx'],
    // 'mydbr_groupsusers' => ['xxx'],
    // 'mydbr_key_column_usage' => ['xxx'],
    'mydbr_languages' => [
        
    ],
    'mydbr_licenses' => [
        
    ],
    'mydbr_param_queries' => [
        
    ],
    // 'mydbr_remote_servers' => ['xxx'],
    // 'mydbr_report_extensions' => ['xxx'],
    // 'mydbr_reports_priv' => ['xxx'],
    // 'mydbr_scheduled_tasks' => ['xxx'],
    'mydbr_snippets' => [
        
    ],
    // 'mydbr_statistics' => ['xxx'],
    'mydbr_styles' => [
        
    ],
    // 'mydbr_sync_exclude' => ['xxx'],
    'mydbr_template_folders' => [
        
    ],
    // 'mydbr_templates' => ['xxx'],
    // 'mydbr_ui_category_collapse' => ['xxx'],
    'mydbr_update' => [
        
    ],
    'mydbr_user_agents' => [
        
    ],
    // 'mydbr_user_logins' => ['xxx'],
    'mydbr_userlogin' => [
        
    ],
    'mydbr_version' => [
        
    ],
    // 'note_frais' => ['xxx'],
    // 'note_frais_detail' => ['xxx'],
    // 'note_frais_justificatif' => ['xxx'],
    // 'offre_detail' => ['xxx'],
    // 'offre_entete' => ['xxx'],
    // 'parc' => ['xxx'],
    // 'prepa_mailing' => ['xxx'],
    // 'reclamation' => ['xxx'],
    'settings' => [
        'ID_SETTINGS',
        'ADDRESS2_FIABILIS',
        'ADDRESS_FIABILIS',
        'BELGIAN_OPTION',
        'BIC',
        'CHILEAN_OPTION',
        'CITY_FIABILIS',
        'CLIENT_REVIEW_LABEL',
        'COMPANY_NAME',
        'CONTRACT_COUNTER_PREFIX',
        'CONTRACT_DUNNING_PERIOD',
        'CONTRACT_DURATION',
        'COUNTRY',
        'CREDIT_NOTE_COUNTER_PREFIX',
        'DUTCH_OPTION',
        'FISCAL_NAME_1',
        'FISCAL_NAME_2',
        'FISCAL_NAME_3',
        'FRENCH_OPTION',
        'IBAN',
        'ID_FIABILIS',
        'INVOICE_COUNTER_PREFIX',
        'ITALIAN_OPTION',
        'MILES_RATES',
        'MISSION_AUDIT_REPORT_COUNTER_PREFIX',
        'MISSION_COUNTER_PREFIX',
        'MISSION_PM_NAME',
        'MISSION_SHOW_COORDINATOR',
        'NACE_NAME',
        'OPPORTUNITY_COUNTER_PREFIX',
        'POLISH_OPTION',
        'SAGE_NO_PIECE_FCG',
        'SAGE_NO_PIECE_JIB',
        'SAGE_NO_PIECE_PRAE',
        'SHOW_FISCAL_2',
        'SHOW_FISCAL_3',
        'SPANISH_OPTION',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TURNOVER_NAME',
        'TURNOVER_NAME_2',
        'TWITTER_WIDGET',
        'VAT_NUMBER_FIABILIS',
        'VAT_RATE',
        'WORKFORCE_NAME',
        'WORKFORCE_NAME_2',
        'ZIP_CODE_FIABILIS',
        'GENERIC_GROUP_INACTIVITY_TIME_1',
        'GENERIC_GROUP_INACTIVITY_TIME_2',
        'GENERIC_GROUP_INACTIVITY_TIME_3',
        'GENERIC_GROUP_STARTING_DATE',
        'GERMAN_OPTION',
    ],
    // 'sms' => ['xxx'],
    // 'societe_commission_paritaire' => ['xxx'],
    'societe_famille' => [
        'ID_SOCIETE_FAMILLE',
        'PID_IDENTIFICATION',
        'COMMERCIAL',
        'DATE_SIGNATURE',
        'FAMILLE',
        'FIN_CONTRAT',
        'HORS_CIBLE',
        'NIVEAU',
        'QUALIFIED',
        'SYS_DATE_CREATION',
        'SYS_DATE_MODIFICATION',
        'SYS_HEURE_CREATION',
        'SYS_HEURE_MODIFICATION',
        'SYS_SYNCHRO_CODE_POSTE',
        'SYS_SYNCHRO_DATE_ENREG',
        'SYS_USER_CREATION',
        'SYS_USER_MODIFICATION',
        'TYPE',
    ],
    // 'societe_subvenciones' => ['xxx'],
    // 'suspects' => ['xxx'],
    // 'sys_cube' => ['xxx'],
    // 'sys_droits_taches' => ['xxx'],
    // 'sys_droits_users' => ['xxx'],
    // 'sys_exchange_deleted' => ['xxx'],
    // 'sys_exchange_journal' => ['xxx'],
    // 'sys_filtrage_users' => ['xxx'],
    // 'sys_formulaire_personnalise' => ['xxx'],
    // 'sys_google_date_synchro' => ['xxx'],
    // 'sys_google_journal' => ['xxx'],
    'sys_groupes_users' => [
        
    ],
    'sys_histo_navigation' => [
        
    ],
    'sys_notifications' => [
        
    ],
    // 'sys_notifications_erreurs' => ['xxx'],
    // 'sys_planning_jours_indisponibles' => ['xxx'],
    'sys_requetes_memorisees' => [
        
    ],
    // 'sys_rgpd_bdd' => ['xxx'],
    // 'sys_rgpd_champs' => ['xxx'],
    // 'sys_rgpd_tables' => ['xxx'],
    // 'sys_synchro_deleted' => ['xxx'],
    // 'sys_synchro_journal' => ['xxx'],
    // 'sys_synchro_parametres' => ['xxx'],
    // 'sys_synchro_parametres_details' => ['xxx'],
    // 'sys_synchro_scripts_instructions' => ['xxx'],
    // 'sys_synchro_scripts_names' => ['xxx'],
    // 'sys_track_emailing' => ['xxx'],
    // 'sys_unsubscribed_emailing' => ['xxx'],
    'sys_users' => [
        
    ],
    'sys_users_connectes' => [
        
    ],
    'sys_users_connectes_historique' => [
        
    ],
    // 'sys_users_dependances' => ['xxx'],
    // 'ticket' => ['xxx'],
    // 'ticket_detail' => ['xxx'],
    // 'ticket_heures' => ['xxx'],
    // 'tliste_action_marketing' => ['xxx'],
    // 'tliste_actions' => ['xxx'],
    // 'tliste_societes' => ['xxx'],
    // 'tmp_eco' => ['xxx'],
];